services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  # Build
  - docker-compose -f docker-compose-build.yaml build --parallel

  # Tagging
  - docker tag udagram-api-feed dongluv/udagram-api-feed:v1
  - docker tag udagram-api-user dongluv/udagram-api-user:v1
  - docker tag udagram-frontend dongluv/udagram-frontend:v1
  - docker tag udagram-reverseproxy dongluv/udagram-reverseproxy:v1

# Tasks to perform after the process is successful. 
after_success:
  # Login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # Push
  - docker push dongluv/udagram-api-feed:v1
  - docker push dongluv/udagram-api-user:v1
  - docker push dongluv/udagram-frontend:v1
  - docker push dongluv/udagram-reverseproxy:v1